/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author LENOVO
 */
public class mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form mainmenu
     */
    public mainmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hitunggajibutton = new javax.swing.JButton();
        datapegawaibutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainmenu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hitung Gaji");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Pegawai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 170, -1));

        hitunggajibutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Screenshots\\Hitung Gaji.png")); // NOI18N
        hitunggajibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitunggajibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(hitunggajibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 160, 130));

        datapegawaibutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Screenshots\\Datakaryawan fix.png")); // NOI18N
        datapegawaibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapegawaibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(datapegawaibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 170, 130));

        logoutbutton.setBackground(new java.awt.Color(0, 0, 153));
        logoutbutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        logoutbutton.setForeground(new java.awt.Color(255, 255, 255));
        logoutbutton.setText("LOG OUT");
        logoutbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutbutton.setMargin(new java.awt.Insets(3, 14, 3, 14));
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\NetBeansProjects\\GajiKaryawan_KLP3\\src\\login\\slipgajirill (5).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
      MenuLogin MenuLogin = new MenuLogin();
      MenuLogin.setVisible(true);
      this.dispose();
        
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void hitunggajibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitunggajibuttonActionPerformed
        menghitunggaji menghitunggaji = new menghitunggaji();
      menghitunggaji.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_hitunggajibuttonActionPerformed

    private void datapegawaibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapegawaibuttonActionPerformed
        datapegawai datapegawai = new datapegawai();
      datapegawai.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_datapegawaibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datapegawaibutton;
    private javax.swing.JButton hitunggajibutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutbutton;
    // End of variables declaration//GEN-END:variables
}
