/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class menghitunggaji extends javax.swing.JFrame {
    int jamkerja, jamlembur, totaljamkerja, hasil;
    /**
     * Creates new form menghitunggaji
     */
    public menghitunggaji() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tunjangantxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        alamattxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbjabatan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        niktxt = new javax.swing.JTextField();
        notelptxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totaljamkerjatxt = new javax.swing.JTextField();
        hitunggajibutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gajipokoktxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gajilemburtxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tunjangan2txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        gajikotortxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jhttxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        nikint = new javax.swing.JLabel();
        pajaktxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        potongantxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        gajibersihtxt = new javax.swing.JTextField();
        jamlemburtxt = new javax.swing.JTextField();
        jamkerjatxt = new javax.swing.JTextField();
        jamkerjabutton = new javax.swing.JButton();
        jamlemburlabel = new javax.swing.JLabel();
        telplabel = new javax.swing.JLabel();
        jemkerjalabel = new javax.swing.JLabel();
        slipgajibutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tunjangan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 30));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 30));

        tunjangantxt.setEnabled(false);
        tunjangantxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjangantxtActionPerformed(evt);
            }
        });
        getContentPane().add(tunjangantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 30));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 30));

        alamattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamattxtActionPerformed(evt);
            }
        });
        getContentPane().add(alamattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 180, 30));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Telp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 30));

        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Direksi", "Direktur Utama", "Manager", "Manager Personalia", "STAFF/Karyawan Tetap", "Karyawan Kontrak" }));
        cbjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjabatanActionPerformed(evt);
            }
        });
        cbjabatan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbjabatanPropertyChange(evt);
            }
        });
        getContentPane().add(cbjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 180, 30));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jabatan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, 30));

        niktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niktxtActionPerformed(evt);
            }
        });
        niktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                niktxtKeyTyped(evt);
            }
        });
        getContentPane().add(niktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 30));

        notelptxt.setText(" ");
        notelptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notelptxtActionPerformed(evt);
            }
        });
        notelptxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                notelptxtKeyTyped(evt);
            }
        });
        getContentPane().add(notelptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 30));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 40));

        namatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namatxtActionPerformed(evt);
            }
        });
        getContentPane().add(namatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 180, 30));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jam Kerja");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, 30));

        totaljamkerjatxt.setEnabled(false);
        totaljamkerjatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaljamkerjatxtActionPerformed(evt);
            }
        });
        getContentPane().add(totaljamkerjatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 30));

        hitunggajibutton.setBackground(new java.awt.Color(204, 255, 255));
        hitunggajibutton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        hitunggajibutton.setText("Hitung Gaji");
        hitunggajibutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitunggajibuttonMouseClicked(evt);
            }
        });
        hitunggajibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitunggajibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(hitunggajibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 100, 50));

        resetbutton.setBackground(new java.awt.Color(204, 255, 255));
        resetbutton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 30));

        jLabel21.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jam Lembur");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 70, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("PENDAPATAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 120, 20));

        jLabel11.setText("Gaji Pokok");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 70, 30));

        gajipokoktxt.setEnabled(false);
        gajipokoktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajipokoktxtActionPerformed(evt);
            }
        });
        getContentPane().add(gajipokoktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 160, 30));

        jLabel12.setText("Gaji Lembur");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, 30));

        gajilemburtxt.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        gajilemburtxt.setEnabled(false);
        gajilemburtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajilemburtxtActionPerformed(evt);
            }
        });
        getContentPane().add(gajilemburtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 160, 30));

        jLabel15.setText("Tunjangan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 60, 30));

        tunjangan2txt.setEnabled(false);
        tunjangan2txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunjangan2txtActionPerformed(evt);
            }
        });
        getContentPane().add(tunjangan2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 160, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setText("JUMLAH PENDAPATAN");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 110, 30));

        gajikotortxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gajikotortxt.setEnabled(false);
        gajikotortxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajikotortxtActionPerformed(evt);
            }
        });
        getContentPane().add(gajikotortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 160, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jLabel14.setText("TOTAL GAJI BERSIH");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 120, 30));

        jLabel17.setText("Jaminan Hari Tua");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 110, 30));

        jhttxt.setEnabled(false);
        jhttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhttxtActionPerformed(evt);
            }
        });
        getContentPane().add(jhttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 160, 30));

        jLabel18.setText("Pajak");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, 30));

        nikint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nikint.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(nikint, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 30));

        pajaktxt.setEnabled(false);
        getContentPane().add(pajaktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 160, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setText("JUMLAH POTONGAN");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 150, 30));

        potongantxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        potongantxt.setEnabled(false);
        getContentPane().add(potongantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 160, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel19.setText("POTONGAN");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 20));

        gajibersihtxt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        gajibersihtxt.setEnabled(false);
        gajibersihtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajibersihtxtActionPerformed(evt);
            }
        });
        getContentPane().add(gajibersihtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 160, 30));

        jamlemburtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamlemburtxtActionPerformed(evt);
            }
        });
        jamlemburtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jamlemburtxtKeyTyped(evt);
            }
        });
        getContentPane().add(jamlemburtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 40, 30));

        jamkerjatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamkerjatxtActionPerformed(evt);
            }
        });
        jamkerjatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jamkerjatxtKeyTyped(evt);
            }
        });
        getContentPane().add(jamkerjatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 40, 30));

        jamkerjabutton.setBackground(new java.awt.Color(204, 204, 204));
        jamkerjabutton.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jamkerjabutton.setText("Hitung Total Jam Kerja");
        jamkerjabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamkerjabuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jamkerjabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, 30));

        jamlemburlabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jamlemburlabel.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jamlemburlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 40, 30));

        telplabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        telplabel.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(telplabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 30, 30));

        jemkerjalabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jemkerjalabel.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jemkerjalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 20, 30));

        slipgajibutton.setBackground(new java.awt.Color(255, 51, 51));
        slipgajibutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slipgajibutton.setForeground(new java.awt.Color(255, 255, 255));
        slipgajibutton.setText("Lihat Slip Gaji");
        slipgajibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slipgajibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(slipgajibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        backbutton.setBackground(new java.awt.Color(204, 255, 255));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\Digital Agency How To Start Business Youtube Thumbnail (600 x 375 px) (700 x 449 px) (2).png")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void niktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niktxtActionPerformed

    private void tunjangantxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjangantxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunjangantxtActionPerformed

    private void alamattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamattxtActionPerformed

    private void cbjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjabatanActionPerformed
        String nilaicbjabatan = (String) cbjabatan.getSelectedItem();
        String teks;
        teks ="";

        switch(nilaicbjabatan){
            case "Pilih" :
            teks = "";
            tunjangantxt.setText(teks);
            break;
            
            case "Direksi" :
            teks = "7000000";
            tunjangantxt.setText(teks);
            break;

            case "Direktur Utama" :
            teks = "6000000";
            tunjangantxt.setText(teks);
            break;

            case "Manager" :
            teks = "4000000";
            tunjangantxt.setText(teks);
            break;

            case "Manager Personalia" :
            teks = "3000000";
            tunjangantxt.setText(teks);
            break;

            case "STAFF/Karyawan Tetap" :
            teks = "1800000";
            tunjangantxt.setText(teks);
            break;

            case "Karyawan Kontrak" :
            teks = "1000000";
            tunjangantxt.setText(teks);
            break;
        }

    }//GEN-LAST:event_cbjabatanActionPerformed

    private void cbjabatanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbjabatanPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjabatanPropertyChange

    private void notelptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notelptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notelptxtActionPerformed

    private void namatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namatxtActionPerformed

    private void totaljamkerjatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaljamkerjatxtActionPerformed

    }//GEN-LAST:event_totaljamkerjatxtActionPerformed

    private void hitunggajibuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitunggajibuttonMouseClicked

    }//GEN-LAST:event_hitunggajibuttonMouseClicked

    private void hitunggajibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitunggajibuttonActionPerformed
      if (namatxt.getText().isEmpty() || niktxt.getText().isEmpty() || alamattxt.getText().isEmpty() || notelptxt.getText().isEmpty() || totaljamkerjatxt.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "DATA ANDA BELUM LENGKAP", "SOMETHING WRONG", JOptionPane.ERROR_MESSAGE);
      } else {
          String nilaicbjabatan = (String) cbjabatan.getSelectedItem();
        String hasil = totaljamkerjatxt.getText();
        int totaljamkerja  = Integer.parseInt(hasil);
        int gajipokok= 0;
        int gajilembur = 0;
      

        switch(nilaicbjabatan){
            case "Direksi" :
                if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 500000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjangandireksi = "7000000";
                    tunjangan2txt.setText(Tunjangandireksi);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjangandireksi);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 5 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 500000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 550000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjangandireksi = "7000000";
                    tunjangan2txt.setText(Tunjangandireksi);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjangandireksi);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 5 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    

                }
            break;

            case "Direktur Utama" :
            if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 425000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjangandirekturutama = "6000000";
                    tunjangan2txt.setText(Tunjangandirekturutama);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjangandirekturutama);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 4 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 425000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 475000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjangandirekturutama = "6000000";
                    tunjangan2txt.setText(Tunjangandirekturutama);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjangandirekturutama);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 4 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    

                }
            break;

            case "Manager" :
            if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 350000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjanganallmanager = "4000000";
                    tunjangan2txt.setText(Tunjanganallmanager );
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjanganallmanager );
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 3 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 350000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 400000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjanganallmanager  = "4000000";
                    tunjangan2txt.setText(Tunjanganallmanager );
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjanganallmanager );
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 3 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
                }
            break;
            
            case "Manager Personalia" :
            if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 300000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjanganhrd = "3000000";
                    tunjangan2txt.setText(Tunjanganhrd);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjanganhrd);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 3 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 300000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 350000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjanganhrd = "3000000";
                    tunjangan2txt.setText(Tunjanganhrd);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjanganhrd);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 3 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    

                }
            break;
            
            case "STAFF/Karyawan Tetap" :
            if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 200000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjanganstaff = "1800000";
                    tunjangan2txt.setText(Tunjanganstaff);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjanganstaff);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 2 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 200000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 250000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjanganstaff = "1800000";
                    tunjangan2txt.setText(Tunjanganstaff);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjanganstaff);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 2 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    

                }
            break;
            
            case "Karyawan Kontrak" :
            if (totaljamkerja <= 40) {
                   gajipokok = totaljamkerja * 100000;
                   String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    String jamlembur = "0";
                    gajilemburtxt.setText(jamlembur);
                    
                    String Tunjangankontrak = "1000000";
                    tunjangan2txt.setText(Tunjangankontrak);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(jamlembur) + Integer.parseInt(Tunjangankontrak);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 1 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    
            
                  } else {
                    gajipokok = 40 * 100000;
                    String gajipokokString = String.valueOf(gajipokok);       
                    gajipokoktxt.setText(gajipokokString);
                    
                    gajilembur = (totaljamkerja - 40) * 150000;
                    String gajilemburString = String.valueOf(gajilembur);       
                    gajilemburtxt.setText(gajilemburString);
                    
                    String Tunjangankontrak = "1000000";
                    tunjangan2txt.setText(Tunjangankontrak);
                    
                    int totalPendapatan = gajipokok + Integer.parseInt(gajilemburString) + Integer.parseInt(Tunjangankontrak);
                    String totalPendapatanString = String.valueOf(totalPendapatan);
                    gajikotortxt.setText(totalPendapatanString);
                    
                    int jaminanHariTua = (int) (totalPendapatan * 10 / 100);
                    String jaminanHariTuaString = String.valueOf(jaminanHariTua);
                    jhttxt.setText(jaminanHariTuaString);
                    
                    int pajak = (int) (totalPendapatan * 1 / 100 / 12);
                    String pajakString = String.valueOf(pajak);
                    pajaktxt.setText(pajakString);
                    
                    int totalpotongan =  Integer.parseInt(jaminanHariTuaString) + Integer.parseInt(pajakString);
                    String totalpotonganString = String.valueOf(totalpotongan);
                    potongantxt.setText(totalpotonganString);
                    
                    int gajibersih =  Integer.parseInt(totalPendapatanString) - Integer.parseInt(totalpotonganString);
                    String gajibersihString = String.valueOf(gajibersih);
                    gajibersihtxt.setText("Rp." + gajibersihString);
                    

                }
            break;
                
        }
      
    }//GEN-LAST:event_hitunggajibuttonActionPerformed
    }
    
    
    private void gajipokoktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajipokoktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajipokoktxtActionPerformed

    private void gajilemburtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajilemburtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajilemburtxtActionPerformed

    private void tunjangan2txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunjangan2txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunjangan2txtActionPerformed

    private void jhttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhttxtActionPerformed

    private void gajibersihtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajibersihtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajibersihtxtActionPerformed

    private void jamlemburtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamlemburtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamlemburtxtActionPerformed

    private void jamkerjatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamkerjatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamkerjatxtActionPerformed

    private void jamkerjabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamkerjabuttonActionPerformed
        int hasil =0;
        String angka1 = jamkerjatxt.getText();
        String angka2 = jamlemburtxt.getText();
        int ke1 = Integer.parseInt(angka1);
        int ke2 = Integer.parseInt(angka2);
        hasil = ke1 +ke2;
        totaljamkerjatxt.setText(""+hasil);
        
    }//GEN-LAST:event_jamkerjabuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        namatxt.setText(null);
        niktxt.setText(null);
        alamattxt.setText(null);
        notelptxt.setText(null);
        cbjabatan.setSelectedItem("Pilih");
        tunjangantxt.setText("0");
        jamkerjatxt.setText(null);
        totaljamkerjatxt.setText(null);
        jamlemburtxt.setText(null);
        gajipokoktxt.setText(null);
        gajilemburtxt.setText(null);
        jamlemburtxt.setText(null);
        tunjangan2txt.setText(null);
        gajikotortxt.setText(null);
        jhttxt.setText(null);
        pajaktxt.setText(null);
        potongantxt.setText(null);
        gajibersihtxt.setText(null);
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void gajikotortxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajikotortxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gajikotortxtActionPerformed

    private void niktxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_niktxtKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
            nikint.setText("!!");
        } else {
            nikint.setText("");
        }
            
        
    }//GEN-LAST:event_niktxtKeyTyped

    private void notelptxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notelptxtKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
            telplabel.setText("!!");
        } else {
            telplabel.setText("");
        }
                 
    }//GEN-LAST:event_notelptxtKeyTyped

    private void jamkerjatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamkerjatxtKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
            jemkerjalabel.setText("!!");
        } else {
            jemkerjalabel.setText("");
        }
    }//GEN-LAST:event_jamkerjatxtKeyTyped

    private void jamlemburtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jamlemburtxtKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
            evt.consume();
            jamlemburlabel.setText("!!");
        } else {
            jamlemburlabel.setText("");
        }
    }//GEN-LAST:event_jamlemburtxtKeyTyped

    private void slipgajibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slipgajibuttonActionPerformed
        slipgaji slipgaji = new slipgaji("Nama          :  " + namatxt.getText(), 
                                         "NIK               :  " + niktxt.getText(),
                                         "Alamat         :  " + alamattxt.getText(),
                                         "No Telp       :  " + notelptxt.getText(),
                                         "Jabatan               :  " + cbjabatan.getSelectedItem(),
                                         "Tunjangan          :  " + tunjangantxt.getText(),
                                         "Jam Kerja           :  " + jamkerjatxt.getText(),
                                         "Jam Lembur      :  " + jamlemburtxt.getText(),
                                         "Gaji Pokok                      :  " + gajipokoktxt.getText(),
                                         "Gaji Lembur                   :  " + gajilemburtxt.getText(),
                                         "Tunjangan                      :  " + tunjangan2txt.getText(),
                                         "Jumlah Pendapatan       :  " + gajikotortxt.getText(),
                                         "Jaminan Hari Tua       :  " + jhttxt.getText(),
                                         "Pajak                              :  " + pajaktxt.getText(),
                                         "Jumlah Potongan       :  " + potongantxt.getText(),
                                         "Total Gaji Bersih      : " + gajibersihtxt.getText()
                                          ,"" + namatxt.getText()
        );
      slipgaji.setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_slipgajibuttonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        mainmenu mainmenu = new mainmenu();
      mainmenu.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menghitunggaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menghitunggaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menghitunggaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menghitunggaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menghitunggaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamattxt;
    private javax.swing.JButton backbutton;
    private javax.swing.JComboBox<String> cbjabatan;
    private javax.swing.JTextField gajibersihtxt;
    private javax.swing.JTextField gajikotortxt;
    private javax.swing.JTextField gajilemburtxt;
    private javax.swing.JTextField gajipokoktxt;
    private javax.swing.JButton hitunggajibutton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jamkerjabutton;
    private javax.swing.JTextField jamkerjatxt;
    private javax.swing.JLabel jamlemburlabel;
    private javax.swing.JTextField jamlemburtxt;
    private javax.swing.JLabel jemkerjalabel;
    private javax.swing.JTextField jhttxt;
    private javax.swing.JTextField namatxt;
    private javax.swing.JLabel nikint;
    private javax.swing.JTextField niktxt;
    private javax.swing.JTextField notelptxt;
    private javax.swing.JTextField pajaktxt;
    private javax.swing.JTextField potongantxt;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton slipgajibutton;
    private javax.swing.JLabel telplabel;
    private javax.swing.JTextField totaljamkerjatxt;
    private javax.swing.JTextField tunjangan2txt;
    private javax.swing.JTextField tunjangantxt;
    // End of variables declaration//GEN-END:variables
}
